apiVersion: apps/v1
kind: Deployment
metadata:
  name: grievance-backend
  labels:
    app: grievance-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grievance-backend
  template:
    metadata:
      labels:
        app: grievance-backend
    spec:
      containers:
        - name: grievance-backend
          image: sikindar9/grievance-project-app:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017/mydb
---
apiVersion: v1
kind: Service
metadata:
  name: grievance-backend-service
spec:
  selector:
    app: grievance-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
